title: "Trifosa Simamora"
description: "PhD Candidate in Natural Resources and Environment | Cornell University."
theme: minima

# Your site URL (GitHub domain)
url: "https://trifosaiin.github.io"

header_pages:
  - about.md
  - cv.md
  - photos.md
