title: "Trifosa Simamora"
description: "PhD Candidate in Natural Resources and Environment | Cornell University."
theme: minima

minima:
  hide_site_feed_link: true

url: "https://www.trifosasimamora.com"

header_pages:
  - index.md
  - about.md
  - research.md
  - publications.md
  - teaching.md
  - cv.md
  - fellowship.md
